"""Engineer Agent - Builds landing page and opens GitHub PR."""
import json
import os
import requests
import base64
from base_agent import BaseAgent

class EngineerAgent(BaseAgent):
    """Engineer agent that generates code and manages GitHub interactions."""

    def __init__(self):
        super().__init__("engineer")
        self.github_token = os.environ.get("GITHUB_TOKEN")
        self.github_repo = os.environ.get("GITHUB_REPO")
        self.headers = {
            "Authorization": f"token {self.github_token}",
            "Accept": "application/vnd.github+json"
        }

    def generate_landing_page(self, product_spec: dict) -> str:
        """Use LLM to generate HTML landing page."""
        print(f"\n💻 Engineer: Generating landing page HTML...")

        system_prompt = """You are a web developer. Generate a beautiful, modern HTML landing page.
Return ONLY the HTML code, no markdown, no explanations.
Include: header with headline/subheadline, features section, call-to-action button, basic CSS styling."""

        value_prop = product_spec.get("value_proposition", "Amazing Product")
        features = product_spec.get("features", [])
        features_text = "\n".join([f"• {f.get('name', '')}: {f.get('description', '')}"
                                   for f in features[:5]])

        user_prompt = f"""Create a landing page HTML for:
Title: {value_prop}

Features:
{features_text}

Requirements:
- Modern, professional design
- Responsive CSS
- Clear call-to-action button
- Feature showcase section
- Return ONLY valid HTML"""

        response = self.call_llm(system_prompt, user_prompt)
        return response.strip()

    def create_github_issue(self, title: str, body: str) -> str:
        """Create a GitHub issue."""
        print(f"\n📝 Engineer: Creating GitHub issue...")

        url = f"https://api.github.com/repos/{self.github_repo}/issues"
        data = {
            "title": title,
            "body": body
        }

        try:
            response = requests.post(url, json=data, headers=self.headers)
            if response.status_code == 201:
                issue = response.json()
                issue_url = issue["html_url"]
                issue_number = issue["number"]
                print(f"✅ Issue created: #{issue_number}")
                return issue_url
            else:
                print(f"⚠️  Issue creation failed: {response.status_code}")
                return f"https://github.com/{self.github_repo}/issues (pending)"
        except Exception as e:
            print(f"❌ Error creating issue: {str(e)}")
            return f"https://github.com/{self.github_repo}/issues (error)"

    def create_branch_and_commit(self, html_content: str, branch_name: str = "agent-landing-page") -> bool:
        """Create a new branch and commit the HTML file."""
        print(f"\n🔧 Engineer: Creating branch and committing code...")

        try:
            # Get the default branch (main) SHA
            repo_url = f"https://api.github.com/repos/{self.github_repo}"
            repo_response = requests.get(repo_url, headers=self.headers)
            default_branch = repo_response.json().get("default_branch", "main")

            # Get the SHA of the default branch
            ref_url = f"https://api.github.com/repos/{self.github_repo}/git/ref/heads/{default_branch}"
            ref_response = requests.get(ref_url, headers=self.headers)
            base_sha = ref_response.json()["object"]["sha"]

            # Create new branch
            branch_url = f"https://api.github.com/repos/{self.github_repo}/git/refs"
            branch_data = {
                "ref": f"refs/heads/{branch_name}",
                "sha": base_sha
            }
            branch_response = requests.post(branch_url, json=branch_data, headers=self.headers)

            if branch_response.status_code not in [201, 422]:  # 422 means branch already exists
                print(f"⚠️  Branch creation issue: {branch_response.status_code}")
                return False

            # Commit the HTML file
            file_path = "index.html"
            content_url = f"https://api.github.com/repos/{self.github_repo}/contents/{file_path}"

            content_b64 = base64.b64encode(html_content.encode()).decode()
            commit_data = {
                "message": "Add landing page generated by Engineer Agent",
                "content": content_b64,
                "branch": branch_name,
                "committer": {
                    "name": "EngineerAgent",
                    "email": "agent@launchmind.ai"
                }
            }

            commit_response = requests.put(content_url, json=commit_data, headers=self.headers)

            if commit_response.status_code in [201, 200]:
                print(f"✅ Code committed to branch {branch_name}")
                return True
            else:
                print(f"⚠️  Commit failed: {commit_response.status_code}")
                return False

        except Exception as e:
            print(f"❌ Error in branch/commit: {str(e)}")
            return False

    def open_pull_request(self, branch_name: str = "agent-landing-page", pr_title: str = None, pr_body: str = None) -> str:
        """Open a GitHub pull request."""
        print(f"\n📤 Engineer: Opening pull request...")

        try:
            repo_response = requests.get(f"https://api.github.com/repos/{self.github_repo}", headers=self.headers)
            default_branch = repo_response.json().get("default_branch", "main")

            url = f"https://api.github.com/repos/{self.github_repo}/pulls"
            data = {
                "title": pr_title or "Initial landing page",
                "body": pr_body or "Landing page generated by Engineer Agent. Ready for review.",
                "head": branch_name,
                "base": default_branch
            }

            response = requests.post(url, json=data, headers=self.headers)

            if response.status_code == 201:
                pr = response.json()
                pr_url = pr["html_url"]
                pr_number = pr["number"]
                print(f"✅ PR opened: #{pr_number}")
                return pr_url
            else:
                print(f"⚠️  PR creation failed: {response.status_code}")
                print(f"   Response: {response.text[:200]}")
                return f"https://github.com/{self.github_repo}/pulls (pending)"

        except Exception as e:
            print(f"❌ Error opening PR: {str(e)}")
            return f"https://github.com/{self.github_repo}/pulls (error)"

    def run(self):
        """Main engineer agent logic."""
        print(f"\n{'='*60}")
        print(f"🏗️  ENGINEER AGENT STARTING")
        print(f"{'='*60}")

        # Wait for product spec from Product agent
        while True:
            messages = self.get_new_messages()
            for msg in messages:
                if msg.from_agent == "product" and msg.message_type == "task":
                    product_spec = msg.payload
                    print(f"📋 Received product spec")

                    # Generate landing page
                    html_content = self.generate_landing_page(product_spec)

                    # Create GitHub issue
                    issue_url = self.create_github_issue(
                        title="Initial landing page",
                        body=f"Generated landing page for: {product_spec.get('value_proposition', 'Product')}"
                    )

                    # Commit and open PR
                    self.create_branch_and_commit(html_content)
                    pr_url = self.open_pull_request(
                        pr_title="Initial landing page",
                        pr_body=f"Auto-generated landing page for: {product_spec.get('value_proposition', 'Product')}"
                    )

                    # Send result back to CEO
                    self.send_message(
                        to_agent="ceo",
                        message_type="result",
                        payload={
                            "html_content": html_content[:500],  # Truncate for message
                            "issue_url": issue_url,
                            "pr_url": pr_url,
                            "branch": "agent-landing-page"
                        },
                        parent_id=msg.message_id
                    )

                    print(f"✅ Engineer work complete")
                    print(f"   Issue: {issue_url}")
                    print(f"   PR: {pr_url}")
                    return
