"""Engineer Agent - Generates landing page, commits to GitHub, opens PR."""
import json
import os
import re
import base64
import requests
from base_agent import BaseAgent


class EngineerAgent(BaseAgent):
    """Generates HTML, creates GitHub issue, commits code, opens pull request."""

    def __init__(self):
        super().__init__("engineer")
        self.token = os.environ.get("GITHUB_TOKEN", "")
        self.repo = os.environ.get("GITHUB_REPO", "")
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github+json",
        }

    # ── public entry point ───────────────────────────────────────────────
    def run(self, product_spec: dict) -> dict:
        """Generate landing page and push to GitHub. Returns result dict."""

        # 1. Generate HTML via LLM
        html = self._generate_html(product_spec)

        # 2. Create GitHub issue
        issue_url = self._create_issue(product_spec)

        # 3. Create branch + commit
        self._create_branch_and_commit(html)

        # 4. Open PR
        pr_url = self._open_pr(product_spec)

        return {
            "html_content": html[:500],
            "full_html": html,
            "issue_url": issue_url,
            "pr_url": pr_url,
            "branch": "agent-landing-page",
        }

    # ── LLM: generate landing page ──────────────────────────────────────
    def _generate_html(self, spec: dict) -> str:
        print(f"   💻 Engineer: generating HTML landing page via LLM...")

        features_md = "\n".join(
            f"- {f['name']}: {f['description']}" for f in spec.get("features", [])[:5]
        )

        system_prompt = (
            "You are a front-end developer. Generate a single, complete HTML file "
            "(including inline CSS) for a modern landing page. Include: hero with "
            "headline + subheadline, features section, call-to-action button, footer. "
            "Return ONLY the HTML — no markdown fences, no explanations."
        )
        user_prompt = (
            f"Product: {spec.get('value_proposition', 'Amazing product')}\n\n"
            f"Features:\n{features_md}\n\n"
            "Make it professional, responsive, with a gradient hero section."
        )

        html = self.call_llm(system_prompt, user_prompt)
        # Strip markdown fences if present
        html = re.sub(r'^```html?\s*', '', html, flags=re.MULTILINE)
        html = re.sub(r'```\s*$', '', html, flags=re.MULTILINE)
        return html.strip()

    # ── GitHub: create issue ─────────────────────────────────────────────
    def _create_issue(self, spec: dict) -> str:
        print(f"   📝 Engineer: creating GitHub issue...")
        try:
            r = requests.post(
                f"https://api.github.com/repos/{self.repo}/issues",
                headers=self.headers,
                json={
                    "title": "Initial landing page",
                    "body": (
                        f"## Landing Page\n\n"
                        f"Auto-generated by EngineerAgent for:\n\n"
                        f"> {spec.get('value_proposition', 'N/A')}\n\n"
                        f"### Features\n" +
                        "\n".join(f"- {f['name']}" for f in spec.get("features", [])[:5])
                    ),
                },
            )
            if r.status_code == 201:
                url = r.json()["html_url"]
                print(f"   ✅ Issue created: {url}")
                return url
            print(f"   ⚠️  Issue creation returned {r.status_code}: {r.text[:120]}")
        except Exception as e:
            print(f"   ❌ Issue error: {e}")
        return "N/A"

    # ── GitHub: branch + commit ──────────────────────────────────────────
    def _create_branch_and_commit(self, html: str):
        print(f"   🔧 Engineer: creating branch + committing code...")
        branch = "agent-landing-page"
        try:
            # Get default branch SHA
            repo_info = requests.get(
                f"https://api.github.com/repos/{self.repo}", headers=self.headers
            ).json()
            default_branch = repo_info.get("default_branch", "main")

            ref = requests.get(
                f"https://api.github.com/repos/{self.repo}/git/ref/heads/{default_branch}",
                headers=self.headers,
            ).json()
            sha = ref["object"]["sha"]

            # Create branch
            requests.post(
                f"https://api.github.com/repos/{self.repo}/git/refs",
                headers=self.headers,
                json={"ref": f"refs/heads/{branch}", "sha": sha},
            )

            # Commit file
            r = requests.put(
                f"https://api.github.com/repos/{self.repo}/contents/index.html",
                headers=self.headers,
                json={
                    "message": "Add landing page — generated by EngineerAgent",
                    "content": base64.b64encode(html.encode()).decode(),
                    "branch": branch,
                    "committer": {"name": "EngineerAgent", "email": "agent@launchmind.ai"},
                },
            )
            if r.status_code in (200, 201):
                print(f"   ✅ Code committed to branch '{branch}'")
            else:
                print(f"   ⚠️  Commit returned {r.status_code}: {r.text[:120]}")
        except Exception as e:
            print(f"   ❌ Branch/commit error: {e}")

    # ── GitHub: open pull request ────────────────────────────────────────
    def _open_pr(self, spec: dict) -> str:
        print(f"   📤 Engineer: opening pull request...")
        try:
            repo_info = requests.get(
                f"https://api.github.com/repos/{self.repo}", headers=self.headers
            ).json()
            default_branch = repo_info.get("default_branch", "main")

            r = requests.post(
                f"https://api.github.com/repos/{self.repo}/pulls",
                headers=self.headers,
                json={
                    "title": "Add initial landing page",
                    "body": (
                        f"## Initial Landing Page\n\n"
                        f"Generated by **EngineerAgent** (LaunchMind MAS).\n\n"
                        f"**Product:** {spec.get('value_proposition', 'N/A')}\n\n"
                        f"### Changes\n- `index.html` — full landing page with CSS\n"
                    ),
                    "head": "agent-landing-page",
                    "base": default_branch,
                },
            )
            if r.status_code == 201:
                url = r.json()["html_url"]
                print(f"   ✅ PR opened: {url}")
                return url
            print(f"   ⚠️  PR creation returned {r.status_code}: {r.text[:120]}")
        except Exception as e:
            print(f"   ❌ PR error: {e}")
        return "N/A"
